INSERT INTO pizzas (name, description, price) VALUES('Margherita', 'Una pizza classica con salsa di pomodoro, mozzarella fresca, basilico e olio di oliva extravergine', 8.00);
INSERT INTO pizzas (name, description, price) VALUES('Quattro Formaggi', 'Una pizza con una combinazione di quattro formaggi diversi come mozzarella, gorgonzola, parmigiano e taleggio', 11.00);
INSERT INTO pizzas (name, description, price) VALUES('Prosciutto e Funghi', 'Una pizza con salsa di pomodoro, mozzarella fresca, prosciutto cotto e funghi champignon', 10.00);
INSERT INTO pizzas (name, description, price) VALUES('Vegetariana', 'Una pizza senza carne, con salsa di pomodoro, mozzarella fresca, pomodori freschi, peperoni, cipolle rosse, olive nere e origano', 9.00);
INSERT INTO pizzas (name, description, price) VALUES('Salmone Piccante', 'Una pizza con salsa di pomodoro, mozzarella fresca e salame piccante', 10.00);

INSERT INTO ingredients (ingredient) VALUES('cipolla');
INSERT INTO ingredients (ingredient) VALUES('prosciutto');
INSERT INTO ingredients (ingredient) VALUES('wrustel');
INSERT INTO ingredients (ingredient) VALUES('mozzarella');
INSERT INTO ingredients (ingredient) VALUES('olio');
INSERT INTO ingredients (ingredient) VALUES('origano');
INSERT INTO ingredients (ingredient) VALUES('olive');
INSERT INTO ingredients (ingredient) VALUES('sugo');
INSERT INTO ingredients (ingredient) VALUES('tonno');
INSERT INTO ingredients (ingredient) VALUES('melanzane');

INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(1,1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(1,5);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(1,4);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(1,6);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(2,4);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(2,5);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(2,6);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(2,7);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(2,9);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(3,1);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(3,2);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(3,8);
INSERT INTO pizza_ingredient (pizza_id, ingredient_id) VALUES(3,9);